import json, unicodedata
def norm(s):
    s = s.lower()
    s = ''.join(c for c in s if not unicodedata.category(c).startswith('P'))
    return s.split()
ref = norm(open('reference.txt').read()); hyp = norm(open('whisper.txt').read())
assert ref == open('ref_norm.txt').read().split() and hyp == open('hyp_norm.txt').read().split()
rows = []
def add(r, h, op, why): rows.append({"i": len(rows), "ref": r, "hyp": h, "op": op, "why": why})
M = lambda r, h, why='same sound across scripts': add(r, h, 'match', why if r != h else 'same word')
S = lambda r, h, why: add(r, h, 'sub', why)
I = lambda h, why: add('', h, 'ins', why)
for w in 'hello thank you for calling'.split(): M(w, w)
S('tiffingo', 'टिफिनवो', 'g heard as व (tiffin-vo): sound differs')
for w in 'this is'.split(): M(w, w)
for r, h in [('arjun','अर्जुन'),('main','मैं'),('aapki','आपकी'),('kaise','कैसे')]: M(r, h)
M('help', 'help')
for r, h in [('kar','कर'),('sakta','सकता'),('hoon','हूँ')]: M(r, h)
M('ji', 'g', 'ji spelled as letter g, same sound'); M('ji', 'g', 'ji spelled as letter g, same sound')
S('the', 'dub', 'the heard as dub: sound differs')
M('order', 'order')
S('fd2130', 'eighty two one three zero', 'f d heard as eighty; digits 2130 spoken individually')
for w in 'is still preparing'.split(): M(w, w)
M('aur', 'और')
for w in 'status update'.split(): M(w, w)
M('kar', 'कर')
S('deta', 'ली', 'deta heard as ली: sound differs')
for r, h in [('haan','हाँ'),('ji','जी'),('abhi','अभी')]: M(r, h)
S('update', 'अपठे', 'update heard as अपठे (d->ठ, final t lost): sound differs')
I('रखू', 'extra word रखू in hypothesis')
M('hoon', 'हूँ'); M('yaa', 'या'); M('delivery', 'delivery'); M('sahi', 'सही')
for w in 'the order includes'.split(): M(w, w)
for r, h in [('kashmiri','कश्मीरी'),('biryani','बिरयानी'),('aur','और')]: M(r, h)
I('बरहानी', 'extra word बरहानी in hypothesis')
M('ji', 'जी')
for w in 'the order'.split(): M(w, w)
M('fd2130', 'f d two one three zero', 'letters and digits spoken individually, same sound')
M('includes', 'includes')
for r, h in [('kashmiri','कश्मीरी'),('biryani','बिरयानी')]: M(r, h)
S('burhalia', 'बरहालिया', 'u of bur- dropped (बर): sound differs')
S('raita', 'रेहिता', 'raita heard as रेहिता (extra hi syllable): sound differs')
M('aur', 'और')
for w in 'coca cola'.split(): M(w, w)
M('ji', 'जी'); M('bilkul', 'बिलकुल')
for w in 'the coca cola is included in the delivery price of'.split(): M(w, w)
RS = ('rs 720', 'seven hundred twenty रुपए', 'rs 720 spoken as seven hundred twenty रुपए (currency word after number), same sound')
M(*RS); M('ji', 'जी')
for w in 'the total fare is'.split(): M(w, w)
M(*RS); M('aur', 'और')
for w in 'the order is'.split(): M(w, w)
S('updated', 'appear', 'updated heard as appear: sound differs')
for w in 'in progress'.split(): M(w, w)
M('ka', 'का'); I('है', 'extra word है in hypothesis'); M('ji', 'जी')
for w in 'the order total is'.split(): M(w, w)
M(*RS); M('aur', 'और'); M('status', 'status'); M('abhi', 'अभी')
S('update', 'uptail', 'update heard as uptail (d->t, te->tail): sound differs')
for r, h in [('kar','कर'),('deta','देता'),('hoon','हूँ'),('ji','जी')]: M(r, h)
for w in 'thank you for calling'.split(): M(w, w)
M('tiffingo', 'tiffin go', 'compound written as two words, same sound')
for w in 'have a good day'.split(): M(w, w)
M('ji', 'जी')
for h in 'टी बी जी इनमें आप ही प्राहि सही है thank you जायकु'.split(): I(h, 'trailing extra word in hypothesis (not in reference)')

R = ' '.join(x['ref'] for x in rows if x['ref']).split(); H = ' '.join(x['hyp'] for x in rows if x['hyp']).split()
assert R == ref, 'ref mismatch'; assert H == hyp, 'hyp mismatch'
c = {k: sum(x['op'] == k for x in rows) for k in ('match','sub','del','ins')}
m = {"pair": "V1_A__food_11_g2", "ref_words": len(ref), "hyp_words": len(hyp), **c,
     "wer": round((c['sub']+c['del']+c['ins'])/len(ref), 6), "ref_norm": ' '.join(ref), "hyp_norm": ' '.join(hyp)}
with open('word_map.jsonl','w') as f:
    for x in rows: f.write(json.dumps(x, ensure_ascii=False)+'\n')
json.dump(m, open('word_metrics.json','w'), ensure_ascii=False, indent=2)
with open('word_map.txt','w') as f:
    f.write(f"{'i':>3}  {'op':<5}  {'ref':<12}  {'hyp':<26}  why\n")
    for x in rows: f.write(f"{x['i']:>3}  {x['op']:<5}  {x['ref']:<12}  {x['hyp']:<26}  {x['why']}\n")
    f.write(f"\nref_words={len(ref)} match={c['match']} sub={c['sub']} del={c['del']} ins={c['ins']} WER={m['wer']}\n")
print({k:v for k,v in m.items() if 'norm' not in k})
