export const meta = {
  name: 'cer-trelis-hinglish-score',
  description: 'Transcribe the 10 CER-study model outputs with the Trelis Whisper-Hinglish fine-tune, then rerun all three CER/WER techniques (score.py raw/fold, romanise-then-score, cross-script char/word maps) and compare with Whisper large-v3',
  phases: [
    { title: 'Transcribe', detail: 'find model, download, transcribe 10 wavs on pod GPU' },
    { title: 'Method 1', detail: 'romanise (blind) -> CER/WER -> verify' },
    { title: 'Method 2', detail: 'char map -> word map -> verify' },
    { title: 'Compare', detail: 'score.py raw/fold + both methods vs large-v3 results; audit; write report' },
  ],
}
const D = '/path/to/cer_study'  // was the laptop hinglish/cer_study dir; set before running
const T = D + '/trelis'
const NORM = `NORMALISATION (identical for reference and hypothesis): lowercase; replace any character that is not a letter or digit or apostrophe with a space; collapse whitespace; strip. CER = Levenshtein over characters of the normalised strings INCLUDING single spaces / number of normalised reference characters. WER = word-level Levenshtein / number of reference words. Report S/D/I. Implement Levenshtein yourself in python3 (stdlib) and run it; never estimate by eye.`
const R = { type: 'object', properties: { status: { type: 'string' }, report: { type: 'string' }, key_facts: { type: 'array', items: { type: 'string' } } }, required: ['status', 'report', 'key_facts'] }
const ROMAN = { type: 'object', properties: { roman: { type: 'string' }, notes: { type: 'string' } }, required: ['roman', 'notes'] }
const SC = { type: 'object', properties: { cer: { type: 'number' }, wer: { type: 'number' }, cer_S: { type: 'integer' }, cer_D: { type: 'integer' }, cer_I: { type: 'integer' }, ref_chars: { type: 'integer' }, wer_S: { type: 'integer' }, wer_D: { type: 'integer' }, wer_I: { type: 'integer' }, ref_words: { type: 'integer' } }, required: ['cer', 'wer', 'cer_S', 'cer_D', 'cer_I', 'ref_chars', 'wer_S', 'wer_D', 'wer_I', 'ref_words'] }
const V1S = { type: 'object', properties: { cer_ok: { type: 'boolean' }, wer_ok: { type: 'boolean' }, romanisation_faithful: { type: 'boolean' }, issues: { type: 'array', items: { type: 'string' } } }, required: ['cer_ok', 'wer_ok', 'romanisation_faithful', 'issues'] }
const CM = { type: 'object', properties: { cer: { type: 'number' }, sub: { type: 'integer' }, del: { type: 'integer' }, ins: { type: 'integer' }, ref_chars: { type: 'integer' }, notes: { type: 'string' } }, required: ['cer', 'sub', 'del', 'ins', 'ref_chars', 'notes'] }
const WM = { type: 'object', properties: { wer: { type: 'number' }, sub: { type: 'integer' }, del: { type: 'integer' }, ins: { type: 'integer' }, ref_words: { type: 'integer' }, notes: { type: 'string' } }, required: ['wer', 'sub', 'del', 'ins', 'ref_words', 'notes'] }
const V2S = { type: 'object', properties: { maps_valid: { type: 'boolean' }, cer_recount: { type: 'number' }, wer_recount: { type: 'number' }, judgement_errors_in_sample: { type: 'integer' }, sample_size: { type: 'integer' }, issues: { type: 'array', items: { type: 'string' } } }, required: ['maps_valid', 'cer_recount', 'wer_recount', 'judgement_errors_in_sample', 'sample_size', 'issues'] }

phase('Transcribe')
const tr = { status: 'done', report: 'Transcription already done by the orchestrator; see research/asr_cer/cer_study/trelis/TRANSCRIBE.md (Trelis/whisper-hinglish-preview, <|hi|><|mixedcode|> prompt, 28 s chunks). Output is mixed script with numbers as English words.', key_facts: [] }
if (!tr || tr.status !== 'done') { log('transcription did not complete; stopping before scoring'); return { tr, stopped: true } }

const pairs = args
const both = await parallel(pairs.map(p => () => Promise.all([
  // Method 1
  agent(`Transliterate ONE speech-recognition transcript of a Hinglish customer-support agent into typed Roman Hinglish (kya, hai, aapka, kaise, bataiye; no diacritics). Devanagari words -> Roman Hinglish; English words written in Devanagari -> normal English spelling; words already in Latin script stay EXACTLY as they are (if the whole transcript is already Roman, return it unchanged apart from nothing); keep numbers and every word in order; do NOT add, drop, correct or fix anything. Read ONLY ${T}/inputs/${p.pair_id}.whisper.txt with the Read tool; never open *.reference.txt or look for the reference anywhere. Return 'roman' and ambiguous-word 'notes'.`, { label: `m1-roman:${p.pair_id}`, phase: 'Method 1', schema: ROMAN })
    .then(r => agent(`Compute CER and WER for pair ${p.pair_id}. REFERENCE = file ${T}/inputs/${p.pair_id}.reference.txt . HYPOTHESIS (verbatim):\n<<<\n${r ? r.roman : ''}\n>>>\n${NORM}\nWrite to ${T}/m1/${p.pair_id}/ (mkdir -p): reference.txt, whisper_original.txt (copy of ${T}/inputs/${p.pair_id}.whisper.txt), whisper_roman.txt (hypothesis exactly), romanisation_notes.txt (${JSON.stringify(r ? r.notes : '')}), score.py (your script), metrics.json. Return numbers.`, { label: `m1-score:${p.pair_id}`, phase: 'Method 1', schema: SC }))
    .then(s => agent(`Independently verify CER/WER for pair ${p.pair_id} in ${T}/m1/${p.pair_id}/ with your OWN Levenshtein and this normalisation: ${NORM} Must match metrics.json to 4 decimals. Check whisper_roman.txt is a faithful transliteration of whisper_original.txt (nothing added/dropped/reordered/corrected; Latin words unchanged). Write verify.json there.`, { label: `m1-verify:${p.pair_id}`, phase: 'Method 1', schema: V1S }).then(v => ({ s, v }))),
  // Method 2
  agent(`Pair ${p.pair_id}. REFERENCE = model text stream in Roman Hinglish: ${T}/inputs/${p.pair_id}.reference.txt . HYPOTHESIS = Trelis Whisper-Hinglish transcript of the model audio: ${T}/inputs/${p.pair_id}.whisper.txt (may be Roman, Devanagari or mixed). Work in ${T}/m2/${p.pair_id}/ (mkdir -p; copy both as reference.txt / whisper.txt). Write a CHARACTER-LEVEL alignment map aligned by SOUND across scripts: char_map.jsonl with one object per step {"i","ref","hyp","op":"match"|"sub"|"del"|"ins","why"}; reference units = characters of the reference after lowercase, dropping punctuation, collapsing whitespace (spaces are units); hypothesis likewise (Devanagari at akshara granularity where needed). 'match' = same sound in context (conventional Hinglish spellings like aa~ा count); 'sub' = different sound. Concatenated ref fields must equal the normalised reference exactly and hyp fields the normalised hypothesis exactly — verify with a script and fix until true. Be consistent: do NOT count silent letters/digraphs as free matches with empty hyp unless the sound is genuinely present; numbers vs number-words: match only if it is the same number. CER=(sub+del+ins)/ref chars. Write char_metrics.json and char_map.txt (ref/hyp/op lines). Use python3 scripts you save in the folder.`, { label: `m2-char:${p.pair_id}`, phase: 'Method 2', schema: CM })
    .then(c => agent(`Pair ${p.pair_id}, folder ${T}/m2/${p.pair_id}/ (reference.txt, whisper.txt, char_map.jsonl exist). Write a WORD-LEVEL map word_map.jsonl ({"i","ref","hyp","op","why"}) aligned by sound across scripts; reference/hypothesis words = whitespace tokens after lowercase + dropping punctuation; a word whose sound differs (per the char map) is 'sub', not 'match'. Joined ref/hyp fields must reproduce the normalised word sequences (check by script). WER=(sub+del+ins)/ref words. Write word_metrics.json and word_map.txt.`, { label: `m2-word:${p.pair_id}`, phase: 'Method 2', schema: WM }).then(w => ({ c, w })))
    .then(cw => agent(`Adversarially verify the maps in ${T}/m2/${p.pair_id}/: own script checks joins reproduce both normalised texts (char + word), recount ops, recompute CER/WER; audit 30 char steps + 20 word steps (all op types; non-obvious cross-script matches) for correct labels by sound; count wrong labels. Write verify.json.`, { label: `m2-verify:${p.pair_id}`, phase: 'Method 2', schema: V2S }).then(v => ({ ...cw, v }))),
]).then(([m1, m2]) => ({ pair_id: p.pair_id, m1, m2 }))))

phase('Compare')
const cmp = await agent(`Write the comparison for the Trelis Whisper-Hinglish re-run of the CER/WER study.
Inputs: ${T}/inputs/ (Trelis transcripts), ${T}/TRANSCRIBE.md, ${T}/m1/<pair>/ (metrics.json, verify.json), ${T}/m2/<pair>/ (char_metrics.json, word_metrics.json, verify.json); earlier large-v3 study: ${D}/comparison.csv, ${D}/COMPARISON.md, ${D}/inputs/<pair>.whisper.txt.
1. score.py raw/fold on the Trelis transcripts: compute with the project's own functions — import raw_norm, fold, cer from hinglish/tests/score.py (monorepo: research/eval_harness/score.py) (sys.path insert; if import side-effects fail, copy those functions verbatim with their deva_to_latin table) — reference = ${T}/inputs/<pair>.reference.txt.
2. Write ${T}/compare_trelis.py producing ${T}/comparison_trelis.csv: per pair and per-model means (base, V1_A, V1_B, V1_C) for Trelis {scorepy raw, fold, m1 CER/WER, m2 CER/WER, verification flags, m2 judgement error rate} next to the large-v3 values from ${D}/comparison.csv; deltas (Trelis - large-v3).
3. Audit your own table once by recomputing 3 random pairs from the metrics files.
4. Write ${T}/COMPARISON_TRELIS.md: model used (repo id, settings, output script), the table (pairs + means), what changed vs large-v3 per method (facts: which pairs/models move, by how much, rank agreement between ASR models per method), how transcript script (Roman vs Devanagari) affected each method, reliability notes from the verify files, files. Facts only. Then open it: setsid gedit ${T}/COMPARISON_TRELIS.md >/dev/null 2>&1 &
Transcription facts: ${tr ? tr.report + ' | ' + tr.key_facts.join(' | ') : '(see TRANSCRIBE.md)'}
Return a <=150-word summary with per-model mean CER/WER for each method, Trelis vs large-v3.`, { label: 'compare', phase: 'Compare', schema: R })
return { tr, cmp, n: both.filter(Boolean).length }
